### ISSUE TITLE
Submit button refreshes page

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#106]
seriously WTF

edit: any trigger of submit (including the enter key) will refresh

**Comment by sdaitzman** [comment]
OK so here's what happened:

I switched to importing the glob `"_*.js"` so we don't have to manually declare all our frontend JS for it to be included in builds. This way, we just name the files _<something>.js and put them in the right place. This excluded scripts.js, which had the code that forces the behavior we want in the form. This issue is fixed in a17e25c
